### PR TITLE
Updates src/MOM6 and src/SIS2 for use with fms2_io

### PR DESCRIPTION
**Pull request by thomas-robinson**
This updates [ESM4-maintenance](https://github.com/NOAA-GFDL/MOM6-examples/commit/2778d3566e01cea2b228ce801a6df6e2a69b16a2) to be compatible with fms2_io.  It cherry-picks @nikizadehgfdl updates that are needed in mom and sis.  This needs to be updated for the [EMS4 public model](https://github.com/NOAA-GFDL/ESM4)

### CODE REVIEW

**Comment by marshallward** [comment]
I can't find hashes for these versions of MOM6 and SIS2 in our repositories.  Are there changes from @nikizadehgfdl that are not yet merged?
 
If not, would be better to first get them in the main branches, or at least identify a commit in NOAA-GFDL/{MOM6,SIS2} with the required changes?

**Comment by thomas-robinson** [comment]
These commits are cherry-picked from @nikizadehgfdl 's fork.  My understanding is that these are the minimum changes needed for compatibility with fms2_io.  
Is there an ESM4-maintenance branch in MOM6 and SIS2 to merge Niki's changes into?

**Comment by nikizadehgfdl** [comment]
These cherrypicks are NOT needed for dev/gfdl as dev/gfdl already has them in some form.
These are only needed for ESM4-maintanance branch to run with FMS202* and preserving the ESM4.0/CM4.0 CMIP6 answers.
dev/gfdl compiles/runs with FMS202* but it changes ESM4.0/CM4.0 answers (due to a vast number of MOM6 updates between ESM4-maintanance branch and FMS2 support ).

**Comment by marshallward** [comment]
Thanks @nikizadehgfdl for that explanation.  I am not at all familiar with ESM4 or its maintenance branch, but that makes sense to me.  @thomas-robinson did you create these MOM6/SIS2 commits via cherry-pick?  I cannot find them in Niki's repo either.

It looks like MOM6 and SIS2 have ESM4-maintenance branches, so it's possible these new commits could be added to those branches.

**Comment by thomas-robinson** [comment]
I submitted PRs to [MOM6](https://github.com/NOAA-GFDL/MOM6/pull/56) and [SIS2](https://github.com/NOAA-GFDL/SIS2/pull/166).  Both are on the ESM4-maintenance branch for their repos.

**Pull request merged**
