### PR TITLE
New land_ocean_seaice experiment.

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**
- new example directory for LM3
 - land_ice_ocean_LM3_SIS2/OM_360x320_C180
 - requires update to atmos_null (dev/master on FMS github)
 - INPUT files need to be moved to a centralized location.
 - Just needs first 10days+1hr from the atmos data.

### CODE REVIEW

**Comment by adcroft** [comment]
I'm working on pulling this but once I'm done we will need to retroactively install a preprocessing directory.

Some questions:
 1. What are the linked runscript and XML for?
 1. README says "See ./gather_lm3_data.sh for details." which isn't present.
 1. I see you are renaming files in the links, e.g.
  ` q10.nc -> /lustre/f1/pdata/gfdl_O/datasets/reanalysis/MERRA/q10/q10_merra_1992.nc`
  1. Doesn't the XML have trouble with this?
  1. How do you plan to use a year other than 1992? Shouldn't we link all the MERRA files here (they're only links) and put the full filename (which includes year) in `data_table`?
 1. Directory is called `OM_360x320_C180`, diag_table has `OMz_360x320_C180`. Which do you want? Or `OM4_360x320_C180`?
 1. field_table has "atmos_mod" entries?

**Comment by adcroft** [comment]
Just noticed there's no `ice_model.res.nc` in `INPUT/` but there is in `/lustre/f1/unswept/Matthew.Harrison/MOM6_datasets/C180_OM360x320.071315`. Should it be linked?

**Comment by adcroft** [comment]
Matt, dev/master doesn't exist for atmos_null? Send a commit id/hash...

**Comment by MJHarrison-GFDL** [comment]
git@github.com/NOAA-GFDL/atmos_null/commit/a7b75f3bcbe1ef4efe625edc71843466117ef7c3

**Comment by MJHarrison-GFDL** [comment]
Removed. Cold starting the ice.

**Comment by MJHarrison-GFDL** [comment]
1,2 : Need to consult with @sergeymalyshev and @elenashevliakova . Need to
commit LM3 spin-up.

3. Resetting the link every 1 year segment in production runs. I have XML
for this. I obviously need to add a preprocessing directory!

Part of it is here

https://github.com/NOAA-GFDL/MOM6-examples/tree/user/mjh/FLOR2/tools/python/FLOR2gridGeneration

Needs work to add MERRA download scripts.

4. Done

5. Need to allocate for spec. humidity .  Not sure about cld amt.

**Pull request merged**
