### PR TITLE
Reorganizing the single column model cases

### PR DESCRIPTION
**Pull request by breichl**
This is a step towards reorganizing the single column model cases in MOM6-examples

- Creates new top-level directory in ocean_only called "single_column_models"
 - Moves the old "CVMix_CVM_tests" to "single_column_models/legacy_CVMix"
 - Moves the old "single_column" to "single_column_models/transient_realistic_forcing"
 - Moves the old "SCM_idealized_hurricane" to "single_column_models/transient_idealized_forcing"
 - Creates new "single_column_models/CVMix_VR18" which includes the scripts to run experiments from Van Roekel et al. 2018 KPP CVMix comparison paper.
 - Creates new "single_column_models/LF17" which includes the scripts to run experiments from Reichl and Li (2019/in prep) that are based on Li and Fox-Kemper (2017)

We can discuss during evaluation of this P/R if this is the best directory structure and organization and iterate, but I do want to make sure these two new experiments are available on github.

This is also a bit of a work in progress (I still want to clean up README files, diag scripts, and possibly add some analysis notebooks), but the re-organization aspect is essentially ready for preliminary evaluation.

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
I like the direction that this PR is going, but I would prefer it if we were to avoid adding a fourth level of directories in which the MOM_parameter_doc and other files can be found. Searches are already inconvenient as it is with 3 different levels of directories for these files, and adding a fourth level, as proposed here, would only make that situation worse. Perhaps the proposed "legacy_CVMix" director could be merged into the directory names for the individual directories. The third directory level, describing the vertical coordinate for a particular test, is useful enough to be worth the hassle that comes with it, in my view.

**Comment by adcroft** [comment]
Let's discuss this at the 11:30 team meeting.

@breichl Could you post the old and proposed `tree -d` here in the comments?

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by breichl** [comment]
[NewDirectoryStructure.txt](https://github.com/NOAA-GFDL/MOM6-examples/files/3442705/NewDirectoryStructure.txt)
[OldDirectoryStructure.txt](https://github.com/NOAA-GFDL/MOM6-examples/files/3442706/OldDirectoryStructure.txt)

**Comment by adcroft** [comment]
Current (42 directories, 3 levels deep):
```
single_column
├── BML
│   └── INPUT -> ../INPUT
├── EPBL
│   └── INPUT -> ../INPUT
├── INPUT
│   ├── Arabian
│   ├── BATS
│   ├── Chagos
│   ├── COARE
│   ├── Kerguelen
│   ├── Kuroshio
│   ├── Labrador
│   ├── Mariana
│   ├── Nazca
│   ├── Nino
│   ├── Norwegian
│   ├── PAPA
│   ├── St_Peter_Rock
│   ├── Walvis
│   └── Weddell
└── KPP
    └── INPUT -> ../INPUT
CVmix_SCM_tests
├── common_BML
├── common_EPBL
├── common_KPP
├── cooling_only
│   ├── BML
│   ├── EPBL
│   └── KPP
├── mech_only
│   ├── BML
│   ├── EPBL
│   └── KPP
├── skin_warming_wind
│   ├── BML
│   ├── EPBL
│   └── KPP
└── wind_only
    ├── BML
    ├── EPBL
    └── KPP
idealized_hurricane
└── INPUT
```

Proposed (600 directories, 4 levels deep):
```
single_column_models
├── CVMix_VR18
│   ├── CEW
│   │   ├── EPBL
│   │   └── KPP
│   ├── common
│   ├── CWB_placeholder
│   ├── DC
│   │   ├── EPBL
│   │   └── KPP
│   ├── FC
│   │   ├── EPBL
│   │   └── KPP
│   ├── FCE
│   │   ├── EPBL
│   │   └── KPP
│   ├── FCML
│   │   ├── EPBL
│   │   └── KPP
│   ├── HW
│   │   ├── EPBL
│   │   └── KPP
│   └── WNF
│       ├── EPBL
│       └── KPP
├── legacy_CVMix
│   ├── common_BML
│   ├── common_EPBL
│   ├── common_KPP
│   ├── cooling_only
│   │   ├── BML
│   │   ├── EPBL
│   │   └── KPP
│   ├── mech_only
│   │   ├── BML
│   │   ├── EPBL
│   │   └── KPP
│   ├── skin_warming_wind
│   │   ├── BML
│   │   ├── EPBL
│   │   └── KPP
│   └── wind_only
│       ├── BML
│       ├── EPBL
│       └── KPP
├── LF17
│   ├── analysis
│   │   └── Figs
│   ├── common
│   ├── HF-25_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-50_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m100_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m10_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m200_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m25_WS-10
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m25_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m25_WS-8
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m300_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m500_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m50_WS-10
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m50_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m50_WS-8
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m5_WS-10
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m5_WS-5
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   ├── HF-m5_WS-5_fL20
│   │   ├── DHH85_waveage-0p6
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-0p8
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p0
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   ├── DHH85_waveage-1p2
│   │   │   ├── ePBL-OM4
│   │   │   ├── ePBL-RH18
│   │   │   ├── ePBL-RL19
│   │   │   ├── KPP_CVMix
│   │   │   └── KPP_CVMix-LTLF17
│   │   └── no_waves
│   │       ├── ePBL-OM4
│   │       ├── ePBL-RH18
│   │       ├── ePBL-RL19
│   │       ├── KPP_CVMix
│   │       └── KPP_CVMix-LTLF17
│   └── HF-m5_WS-8
│       ├── DHH85_waveage-0p6
│       │   ├── ePBL-OM4
│       │   ├── ePBL-RH18
│       │   ├── ePBL-RL19
│       │   ├── KPP_CVMix
│       │   └── KPP_CVMix-LTLF17
│       ├── DHH85_waveage-0p8
│       │   ├── ePBL-OM4
│       │   ├── ePBL-RH18
│       │   ├── ePBL-RL19
│       │   ├── KPP_CVMix
│       │   └── KPP_CVMix-LTLF17
│       ├── DHH85_waveage-1p0
│       │   ├── ePBL-OM4
│       │   ├── ePBL-RH18
│       │   ├── ePBL-RL19
│       │   ├── KPP_CVMix
│       │   └── KPP_CVMix-LTLF17
│       ├── DHH85_waveage-1p2
│       │   ├── ePBL-OM4
│       │   ├── ePBL-RH18
│       │   ├── ePBL-RL19
│       │   ├── KPP_CVMix
│       │   └── KPP_CVMix-LTLF17
│       └── no_waves
│           ├── ePBL-OM4
│           ├── ePBL-RH18
│           ├── ePBL-RL19
│           ├── KPP_CVMix
│           └── KPP_CVMix-LTLF17
├── transient_idealized_forcing
│   └── idealized_hurricane
└── transient_realistic_forcing
    ├── BML
    │   └── INPUT -> ../INPUT
    ├── EPBL
    │   └── INPUT -> ../INPUT
    ├── INPUT
    │   ├── Arabian
    │   ├── BATS
    │   ├── Chagos
    │   ├── COARE
    │   ├── Kerguelen
    │   ├── Kuroshio
    │   ├── Labrador
    │   ├── Mariana
    │   ├── Nazca
    │   ├── Nino
    │   ├── Norwegian
    │   ├── PAPA
    │   ├── St_Peter_Rock
    │   ├── Walvis
    │   └── Weddell
    └── KPP
        └── INPUT -> ../INPUT
```

**Comment by breichl** [comment]
Closing this now.  Will reopen later with modified approach per discussion today (reducing the new experiments included).

**Pull request closed without merging**
