### PR TITLE
fix variable straits used before assignment

### PR DESCRIPTION
**Pull request by raphaeldussin**
when no straits data is available, we cannot create nc dim and variable

@jkrasting @nikizadehgfdl

### CODE REVIEW

**Comment by nikizadehgfdl** [comment]
@raphaeldussin this PR needs a couple of more if blocks to work:
```
-      strait_out.setncattr('standard_name','region')
+      if do_mfo:
+         strait_out.setncattr('standard_name','region')

-      strait_out[:] = nc.stringtochar(strait_names)
+      if do_mfo:
+         strait_out[:] = nc.stringtochar(strait_names)
```

**Comment by raphaeldussin** [comment]
done. Hopefully sometime soon we'll rewrite the netcdf I/O with xarray and this will be much cleaner

**Comment by adcroft** [comment]
Had this been tested and is ready to go?

**Comment by nikizadehgfdl** [comment]
Yes, this fix is working.

**Pull request merged**
