### PR TITLE
Om 1deg

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**
This commit removes the land_ice_ocean configuration directory containing a 1 degree ocean experiment and replaces with an ice/ocean experiment (OM_1deg) which uses the SPEAR ocean model configuration.

### CODE REVIEW

**Comment by adcroft** [comment]
This collided (as often happens) with @Hallberg-NOAA changes. I've resolved the conflicts as best I could. Checking it works in the suite now but once all is done would like @MJHarrison-GFDL to double check I didn't change anything the wrong way.

**Comment by MJHarrison-GFDL** [comment]
oops. It's in 

/lustre/f2/dev/Matthew.Harrison/MOM6-examples/ice_ocean_SIS2/OM_1deg/INPUT

**Comment by MJHarrison-GFDL** [comment]
I had this issue when I merged with dev/gfdl . For some reason, is is cross-referencing the OM_1deg directory contents for these files to the pre-existing land_ice... directory.  I don't understand why.

**Comment by adcroft** [comment]
Suggest removing files, commiting and then re-add, commit. Don't forget the symlink .datasets which I had to add too.

**Pull request closed without merging**
