### PR TITLE
User/mjh/om4 05 preprocessing

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**
This commit introduces some changes to the land masks and associated cubed-sphere mosaic files for all tiles with the exception of tile1. This changed was introduced when switching to commit 168f6a5a2717bc of fre-nctools (the previous version of the Makefile used an active branch). Other changes in the bathymetry differ by a small amount (10-3 m) from that used in current development runs (the previous results were uncoverable due to system level changes). New answers should reproduce on the GFDL analysis cluster going forward.

Additional input files for CORE runs include inter-annual runoff from Dai and Trenberth and the surface sailinity restoring file from JRA55-do-suppl

### CODE REVIEW

**Comment by MJHarrison-GFDL** [comment]
@StephenGriffies @jkrasting

**Comment by adcroft** [comment]
Failed with
```
cp: cannot stat `/archive/mjh/gold/datasets/JRA55-do-suppl/woa13_decav_s_0-10m.mon_01v2.nc': No such file or directory
```

**Comment by adcroft** [comment]
Also
```
edit_topog.nc: FAILED
interpolated_topog.nc: OK
mercator_topog_gebco.nc: OK
ncap_topog_gebco.nc: OK
ncap_topog.nc: OK
ocean_topog.nc: FAILED
OM4_topography_edits.nc: OK
so_topog_gebco.nc: OK
topog.nc: FAILED
```

edit_topog.nc is created by combining interpolated_topog.nc (OK) with topo_edits_010518.nc and I believe there are no mathematical operations here so either the recorded checksums are wrong or topo_edits_0105018.nc is wrong.

**Comment by MJHarrison-GFDL** [comment]
The point was to produce a grid which is consistent with what we are actually running.
The new topo_edits file yields answers which are nearly identical to the current production runs

**Comment by adcroft** [comment]
- The clean test overnight still fails for mosaic_ocean.1080x768/atmos_mosaic_tile1Xland_mosaic_tile1.cdl.
- Also, remove OM4_topography_edits.nc from both directory and md5sums.txt .

**Comment by MJHarrison-GFDL** [comment]
OK. I did a refresh on my directory and committed new answers.

**Pull request merged**
